---
title: "UKBB_IEU_Ashley_Distribution of MAF"
author: "Zichong Liu"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
```

```{r}
# Importing data using the fread function of the data.table package
UKBB_IEU <- fread("UKBB_Ashley.tsv")
```

```{r}
head(UKBB_IEU)
```

### Plot the histogram of the MAF distribution

```{r}
UKBB_IEU_p <- ggplot(UKBB_IEU, aes(x = MAF)) +
  geom_histogram(binwidth = 0.0001, fill = "#5B79FB", color = "#5B79FB", alpha = 1.0) +
  labs(title = "Histogram of MAF distribution\n(UKBB IEU)", x = "MAF", y = "The number of SNP") +
  theme(plot.title = element_text(size = 22),  # 标题居中并设置字体大小
        axis.title.x = element_text(size = 26),  # x 轴标题字体大小
        axis.title.y = element_text(size = 26),  # y 轴标题字体大小
        axis.text.x = element_text(size = 20),  # x 轴坐标字体大小
        axis.text.y = element_text(size = 20)) +  # y 轴坐标字体大小
  theme_minimal()
ggsave("Histogram of MAF distribution for UKBB_IEU.png", UKBB_IEU_p, width = 6, height = 5)
```

### Histogram MAF \> 0.001

```{r}
UKBB_IEU <- fread("UKBB_maf0.001.tsv")

UKBB_IEU_p <- ggplot(UKBB_IEU, aes(x = MAF)) +
  geom_histogram(binwidth = 0.0001, fill = "#5B79FB", color = "#5B79FB", alpha = 1.0) +
  labs(title = "Histogram of MAF distribution for UKBB IEU (MAF > 0.001)", x = "MAF", y = "The number of SNP") +
  theme(plot.title = element_text(size = 22),  # 标题居中并设置字体大小
        axis.title.x = element_text(size = 26),  # x 轴标题字体大小
        axis.title.y = element_text(size = 26),  # y 轴标题字体大小
        axis.text.x = element_text(size = 20),  # x 轴坐标字体大小
        axis.text.y = element_text(size = 20)) +  # y 轴坐标字体大小
  theme_minimal()
ggsave("Histogram of MAF distribution for UKBB_IEU MAF 0.001.png", UKBB_IEU_p, width = 6, height = 5)
```

### Histogram in log scale

```{r}
UKBB_IEU <- fread("UKBB_maf0.001.tsv")

UKBB_IEU_p <- ggplot(UKBB_IEU, aes(x = MAF)) +
  geom_histogram(binwidth = 0.0001, fill = "#5B79FB", color = "#5B79FB", alpha = 1.0) +
  scale_y_log10() +
  labs(title = "Histogram of MAF distribution for UKBB_IEU (MAF > 0.001)", x = "MAF", y = "Frequency of MAF") +
  theme_minimal()
ggsave("Histogram of MAF distribution for UKBB_IEU MAF 0.001 log.png", UKBB_IEU_p, width = 10, height = 8)
```

```{r}
head(UKBB_IEU)
```
