---
title: "UKBB_NealeLab Distribution of MAF"
author: "Zichong Liu"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(scales)
```

```{r}
# Importing data using the fread function of the data.table package
UKBB_NealeLab <- fread("NealeLab_rsID_2.tsv")
```

```{r}
head(UKBB_NealeLab)
```

### Derive the top 100 SNPs with the smallest MAFs

```{r}
UKBB_NealeLab_sorted <- UKBB_NealeLab[order(UKBB_NealeLab$minor_AF, decreasing = F), ]
head(UKBB_NealeLab_sorted, 20)
```

```{r}
UKBB_NealeLab_head_MAF <- head(UKBB_NealeLab_sorted, 100)
write.xlsx(UKBB_NealeLab_head_MAF, "UKBB_NealeLab_head_MAF.xlsx")
```

### Plot the histogram of the MAF distribution

```{r}
UKBB_NealeLab_p <- ggplot(UKBB_NealeLab, aes(x = minor_AF)) +
  geom_histogram(binwidth = 0.0001, fill = "#5B79FB", color = "#5B79FB", alpha = 1.0) +
  labs(title = "Histogram of MAF distribution\n(UKBB Neale Lab)", x = "MAF", y = "The number of SNP") +
  theme(plot.title = element_text(size = 22),  # 标题居中并设置字体大小
        axis.title.x = element_text(size = 26),  # x 轴标题字体大小
        axis.title.y = element_text(size = 26),  # y 轴标题字体大小
        axis.text.x = element_text(size = 20),  # x 轴坐标字体大小
        axis.text.y = element_text(size = 20)) +  # y 轴坐标字体大小
  scale_y_continuous(limits = c(0, 150000), labels = function(x) format(x, scientific = FALSE)) +  # y 轴不使用科学计数法
  theme_minimal()
ggsave("Histogram of MAF distribution for UKBB_NealeLab.png", UKBB_NealeLab_p, width = 6, height = 5)
```

### MAF \> 0.001

```{r}
UKBB_NealeLab <- fread("NealeLab_maf0.001.tsv")

UKBB_NealeLab_p <- ggplot(UKBB_NealeLab, aes(x = minor_AF)) +
  geom_density(color = "#5B79FB", alpha = 0.6) +
  scale_y_log10(breaks = c(0, 5, 10, 15, 20, 25, 30, 35)) +  
  coord_cartesian(ylim = c(0.5, 30), xlim = c(0, 0.5)) +  # Setting the y-axis range
  labs(title = "Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.001)", 
       x = "MAF", 
       y = "The number of SNPs (Log Scale)") +
  theme_minimal()

ggsave("Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.001).png", UKBB_NealeLab_p, width = 10, height = 8)
```

### MAF \> 0.01

```{r}
UKBB_NealeLab <- fread("NealeLab_maf0.01.tsv")

UKBB_NealeLab_p <- ggplot(UKBB_NealeLab, aes(x = minor_AF)) +
  geom_density(color = "#5B79FB", alpha = 0.6) +
  scale_y_log10(breaks = c(0, 5, 10, 15, 20, 25, 30, 35)) +  
  coord_cartesian(ylim = c(0.5, 30), xlim = c(0, 0.5)) +  # Setting the y-axis range
  labs(title = "Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.01)", 
       x = "MAF", 
       y = "The number of SNPs (Log Scale)") +
  theme_minimal()

ggsave("Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.01).png", UKBB_NealeLab_p, width = 10, height = 8)
```

### MAF \> 0.05

```{r}
UKBB_NealeLab <- fread("NealeLab_maf0.05.tsv")

UKBB_NealeLab_p <- ggplot(UKBB_NealeLab, aes(x = minor_AF)) +
  geom_density(color = "#5B79FB", alpha = 0.6) +
  scale_y_log10(breaks = c(0, 5, 10, 15, 20, 25, 30, 35)) +  
  coord_cartesian(ylim = c(0.5, 30), xlim = c(0, 0.5)) +  # Setting the y-axis range
  labs(title = "Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.05)", 
       x = "MAF", 
       y = "The number of SNPs (Log Scale)") +
  theme_minimal()

ggsave("Density Plot of MAF distribution for UKBB_NealeLab (MAF > 0.05).png", UKBB_NealeLab_p, width = 10, height = 8)
```

### Histogram MAF \> 0.001

```{r}
UKBB_NealeLab <- fread("NealeLab_maf0.001.tsv")

UKBB_NealeLab_p <- ggplot(UKBB_NealeLab, aes(x = minor_AF)) +
  geom_histogram(binwidth = 0.0001, fill = "#5B79FB", color = "#5B79FB", alpha = 1.0) +
  labs(title = "Histogram of MAF distribution for UKBB_NealeLab (MAF > 0.001)", x = "MAF", y = "The number of SNP") +
  theme_minimal()

ggsave("Histogram of MAF distribution for UKBB_NealeLab MAF 0.001.png", UKBB_NealeLab_p, width = 10, height = 8)
```
